travis:
  secure:
    BINSTAR_TOKEN: U2IQMsJwxu1pe9kCO3OGkDpn0hh486Qlwj+ElcKUe28gGy6oZkGjUeJ60HCJPh90WRhFtWMrbWuWXiR3oTfJF/XQ0nPIJOcIrfYxtu4uxUjM1cX+jlpDk2HEiWNaQcX1MxeIod8GA2+AvcS4kq5mjipZRb/eiTfmjleFBEAeVpPTOQdKp4vSsdFfm/T5h/CxbdlaX+nKuwAtpNcgqUOU+yGdAxk7e72P0/+iEyULr23nClCvhfq02HDmSE5IzGFkdsw2X/1ErDKoSy6GW+4fwBWX0XNHY4loCKIO6hiZGCo+/Ijt/LHeUtW1BJf9TLRwFMsgSWPllU1/v4vQX1q5BQjB279KVcKM3LFHDOB1XOePAIULwWJTJ5ymYqMroMoAE2BXij660scpnXsQrvVB5aSjwA6t2S03oSHHM3gU2SscWbI/VnChQ4VIEpqjVRElpAQ+yFe/dkv9edWbFaZgOr4sYftbUcr8H4DL/xUJiS9NzsTYPQjy9/taJcgYwbl6INUNSIL0GAQQiHLIYKqSqI3CFAkpRrJIaoR91rysisokqDY2sHvxokIv3jvZGv3SZf9QgY2allH1YpGYOABq9tpgYKD/eIsgNYmuU991FrIvEMbZTEQX0FRSY37lTYOHJDYoVPEbpnaD3kzFPi5NkFdoYd+V6WaQkYLDNtbV/Ao=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
